name: 'Get & Cache Dependencies'
description: 'Get Dependencies via npm and cached them.'
runs:
  using: 'composite'
  steps:
   - name: Cache Node.js modules
     id: cache
     uses: actions/cache@v6
     with:
      path: node_modules
      key: dep-node-modules-${{ hashFiles('**/package-lock.json') }}
   - name: install dependencies
     if: steps.cache.outputs.cache-hit != 'true'
     shell: bash
     run: npm ci 