name: 'Get & Cache Dependencies'
description: 'Get Dependencies via npm and cached them.'
inputs:
  caching:
    description: 'Whether to cache dependencies or not.'
    required: false
    default: 'true'
outputs:
  used-cache:
    description: 'Whether the cache was used or not.'
    value: ${{ steps.install-dependencies }}
runs:
  using: 'composite'
  steps:
   - name: Cache Node.js modules
     if: ${{ inputs.caching == 'true' }}
     id: cache
     uses: actions/cache@v6
     with:
      path: node_modules
      key: dep-node-modules-${{ hashFiles('**/package-lock.json') }}
   - name: install dependencies
     id: install-dependencies
     if: ${{ inputs.caching != 'true' || steps.cache.outputs.cache-hit != 'true' }}
     shell: bash
     run: |
       npm ci
       echo "used-cache=false" >> $GITHUB_OUTPUT
