name: Demo Matrix
on:
  push:
    branches:
      - main
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [20.x, 22.x]
        include:
          - operating-system: windows-latest
            node-version: 20.x
            message: "Windows with Node.js 20.x"
        exclude:
          - operating-system: macos-latest
            node-version: 22.x
            message: "macOS with Node.js 22.x"
    runs-on: ${{ matrix.operating-system }}
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build
