name: Deploy Website
on:
  push:
    branches:
      - main
env:
        VITE_DEPLOY_LABEL: github-actions-build
        SEC1: ${{ secrets.SEC1 }}
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/checkout@v6
            - name: Cache Node.js modules
              id: cache-node-modules
              uses: actions/cache@v6
              with:
                path: node_modules
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-
            - name: Set up Node.js(Install dependencies and run tests)
              if: steps.cache-node-modules.outputs.cache-hit != 'true'
              run: npm ci
            - name: Lint code
              run: npm run lint
            - name: Test code
              id: run-tests
              run: npm test
            - name: Upload test results
              continue-on-error: true
            #  if: failure() && steps.run-tests.outcome == 'failure' 
              id: upload-test-results
              uses: actions/upload-artifact@v7
              with:
                name: test-results
                path: test-results.json
    build:
        runs-on: ubuntu-latest
        needs: test
        outputs:
            script-filename: ${{ steps.publish-js-filename.outputs.script-filename }}
        steps:
            - name: Get Code
              uses: actions/checkout@v6
            - name: Cache Node.js modules
              id: cache-node-modules
              uses: actions/cache@v6
              with:
                path: node_modules
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                restore-keys: |
                  ${{ runner.os }}-node-
            - name: Set up Node.js(Install dependencies)
              if: steps.cache-node-modules.outputs.cache-hit != 'true'
              run: npm ci 
            - name: Build website
              run: npm run build
            - name: publish JS filename
              id: publish-js-filename
              run: find dist/assets/*.js -type f -execdir echo 'script-filename={}' >> $GITHUB_OUTPUT ';'
            - name: Upload build artifacts
              uses: actions/upload-artifact@v7
              with:
                name: dist-files
                path: dist
    deploy:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: List files in dist directory before downloading artifacts
              run: |
                echo "=== Current directory ==="
                ls
            - name: Download build artifacts
              uses: actions/download-artifact@v8
              with:
                name: dist-files
            - name: Output script filename
              run: |
                echo "Script filename: ${{ needs.build.outputs.script-filename }}"
            - name: List files in dist directory after downloading artifacts
              run: |
                echo "=== Current directory ==="
                ls -R .
            - name: Get Code
              run: echo "Deploying website..."
            - name: Display Environment Variables
              run: |
                echo "VITE_DEPLOY_LABEL: ${{ env.VITE_DEPLOY_LABEL }}"
            - name: Display Repository Variables
              run: |
                echo "SECRET_1: ${{ env.SEC1 }}"
    report:
        needs: deploy
        if: failure()
        runs-on: ubuntu-latest
        steps:
            - name: Generate Deployment Report
              run: |
                echo "Generating deployment report..."
                echo "Deployment completed successfully."