name: Reusable Workflow
on: 
    workflow_call:
        inputs:
            artifact-name:
                required: true
                type: string
                default: dist-files
        secrets:
            SECRET_1:
                required: true
        outputs:
            result:
                description: 'The result of the job'
                value: ${{ jobs.deploy.steps.set-result.outputs.step-result }}
jobs:
    deploy:
        outputs:
            result_job: ${{ steps.set-result.outputs.job-result }}
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/download-artifact@v6
              with:
                name: ${{ inputs.artifact-name }}
            - name: List files
              run: |
                echo "=== Current directory ==="
                ls
            - name: Display secrets Variables
              run: |
                echo "SECRET_1=${{ secrets.SECRET_1 }}"
            - name: Output Information
              run: echo "Deploying & uploading ..."
            - name: Set result output
              id: set-result
              #run: echo "step-result=dist/assets/main.js" >> $GITHUB_OUTPUT
              run: echo "::set-output name=step-result::success" 