name: Reusable Workflow
on: 
    workflow_call:
        inputs:
            artifact-name:
                required: true
                type: string
                default: dist-files
        secrets:
            SECRET_1:
                required: true
                type: string
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/download-artifact@v6
              with:
                name: ${{ inputs.artifact-name }}
            - name: List files
              run: |
                echo "=== Current directory ==="
                ls
            - name: Display secrets Variables
              run: |
                echo "SECRET_1=${{ secrets.SECRET_1 }}"
            - name: Output Information
              run: echo "Deploying & uploading ..."